FROM python:3.10

WORKDIR /code

COPY requirements.txt /code/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# NEW:
RUN python -m spacy download en_core_web_sm

COPY . /code/

EXPOSE 7860

CMD ["python", "app.py"]
